fix1037_paloalto_panos_show_running_nat-policy
networktocode/ntc-templates pull request #1040
Opened 2021-12-13 10:36 UTC by diepes

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT

ntc_templates/templates/paloalto_panos_show_running_nat-policy.textfsm

##### SUMMARY

SOURCE changed form single IP to list
add -> Error 

Fixes #1037

```
New raw template.
```

2021-12-13 20:54 UTC, alihyder-s reviewed
I have modified the code for DESTINATION as well.  But Still it cant able to process data if there is list in the fields.

Destination : List of Subnets or List of IPs
Source: List of Subnets or List of IPs
From: List
To: List

2021-12-13 20:55 UTC, alihyder-s commented
"Rule 4 Nat-ID 4; index: 8" {
        nat-type ipv4;
        from [ Mgmt Data TRUSTED UNTRUSTED ];
        source [ 10.0.0.0/8 172.0.0.0/16];
        to [ UNTRUSTED DMZ ];
        to-interface ethernet1/5;
        destination [ 1.1.1.1 2.2.2.2 ];
        service 0:any/any/any;
        translate-to "src: 3.3.3.3 (dynamic-ip-and-port) (pool idx: 24)";
        terminal no;

2021-12-13 22:54 UTC, diepes commented
@alihyder-s ok so you are saying here is another example where the destination is a list.

For new we just capture the lists as a string, to keep it backwards compatible, also seems PaloAlto invented there own list format with no commas.

I will add another test for source and destination lists.

```
"Rule 4 Nat-ID 4; index: 8" {
nat-type ipv4;
from [ Mgmt Data TRUSTED UNTRUSTED ];
source [ 10.0.0.0/8 172.0.0.0/16 ];
to [ UNTRUSTED DMZ ];
to-interface ethernet1/5;
destination [ 1.1.1.1 2.2.2.2 ];
service 0:any/any/any;
translate-to "src: 3.3.3.3 (dynamic-ip-and-port) (pool idx: 24)";
terminal no;
```

2021-12-13 23:49 UTC, diepes commented
@alihyder-s please check updated PR - added new example and test.

2022-05-22 19:06 UTC, jmcgill298 requested changes

2022-05-22 19:06 UTC, jmcgill298 commented on ntc_templates/templates/paloalto_panos_show_running_nat-policy.textfsm
> +  ^. -> Error
```suggestion
  ^. -> Error

```

2022-12-19 23:14 UTC, merged