Add Cisco IOS show power inline
networktocode/ntc-templates pull request #1106
Opened 2022-03-21 13:40 UTC by Mathieu-Dirkx

##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
Cisco IOS - show power inline

##### SUMMARY
Add support for show power inline on Cisco IOS platform

2022-03-31 02:42 UTC, jvanderaa commented
@jmcgill298 I believe this is a start on a module set. We had a discussion at one point about what this template would look like. Since the output gives both interface level stats and the entire chassis/virtual switch details.

2022-04-02 22:25 UTC, diepes commented on ntc_templates/templates/cisco_ios_show_power_inline.textfsm
> +  ^Interface\s+Admin\s+Oper\s+Power(\(Watts\))?\s+Device\s+Class.*$$
You can use the heading for the table to jump to new parsing section `^match -> Table`
this keep the header matching and the table parsing separate, less chance of matching something by accident.

2022-04-02 22:28 UTC, diepes commented on ntc_templates/templates/cisco_ios_show_power_inline.textfsm
> +  ^[\s(Wats)]*$$
Spelling mistake, will never match Watts with two t's

2022-04-02 22:39 UTC, diepes commented
@Mathieu-Dirkx please re-base the PR on the master so it becomes a single commit.

2022-05-22 18:59 UTC, jmcgill298 requested changes
see @diepes comments

2022-06-01 07:09 UTC, closed without merging

2022-06-01 07:10 UTC, Mathieu-Dirkx commented
I tried to re-base but nothing changed.
I do not know how to do what you want me to do.
I will no longer waste your time and close the pull-request.