Arista EOS show environment power
networktocode/ntc-templates pull request #1109
Opened 2022-03-31 18:41 UTC by pauljorgenson

##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

Arista EOS `show environment power` command

##### SUMMARY

```

```

2022-04-02 22:19 UTC, diepes commented
Hi @pauljorgenson 
The variable naming does not match with the table headings. The naming and units is not consistent.
e.g.
Table[Output Power]460w  -> power_supply_watts: "460"
Table[Input Current]1.05A -> power_supply_input: "1.05A"

In the one case the Units[w] is dropped and in the other the unit[A] is kept in the output value.
Should we keep the unit in both cases and rename power_supply_watts to power_supply_output ?

Another example is Table[Model] -> power_supply_pid: "PWR-460AC-F" 
would it make sense to rename this to power_supply_model ?

2022-05-22 18:58 UTC, jmcgill298 requested changes

2022-05-22 18:58 UTC, jmcgill298 commented on ntc_templates/templates/arista_eos_show_environment_power.textfsm
> +  ^. -> Error
```suggestion
  ^. -> Error

```

2022-05-22 18:58 UTC, jmcgill298 commented on tests/arista_eos/show_environment_power/arista_eos_show_environment_power1.raw
> +Total --         2000W   --   -- 273.0W --          --
```suggestion
Total --         2000W   --   -- 273.0W --          --

```

2022-05-22 18:58 UTC, jmcgill298 commented on tests/arista_eos/show_environment_power/arista_eos_show_environment_power2.raw
> +2       PWR-460AC-F               460W    1.05A   10.38A   121.0W Ok
```suggestion
2       PWR-460AC-F               460W    1.05A   10.38A   121.0W Ok

```

2022-05-22 18:58 UTC, jmcgill298 commented on tests/arista_eos/show_environment_power/arista_eos_show_environment_power3.raw
> +Total  --             1000W      --      -- 134.8W --                      --
```suggestion
Total  --             1000W      --      -- 134.8W --                      --

```

2022-05-22 18:58 UTC, jmcgill298 commented on tests/arista_eos/show_environment_power/arista_eos_show_environment_power4.raw
> +% There seem to be no power supplies connected.
```suggestion
% There seem to be no power supplies connected.

```

2024-06-19 02:53 UTC, ryanmerolle commented
What is required to push this through. I'd be happy to help

2024-07-09 17:41 UTC, closed without merging

2024-07-09 17:41 UTC, jmcgill298 commented
Fixed requested whitespace updates and rebased to resolve conflicts: https://github.com/networktocode/ntc-templates/pull/1734