Fixes#1048 cisco xr admin show inventory
networktocode/ntc-templates pull request #1118
Opened 2022-04-10 09:08 UTC by diepes

##### ISSUE TYPE
 - Bugfix Pull Request
 - Additional Testing

##### COMPONENT
cisco_xr  admin show inventory

##### SUMMARY
Fixes #1048
1. Add new raw test tests/cisco_xr/admin_show_inventory/cisco_xr_admin_show_inventory2.yml
   *  update parsing

3. Small fix on existing template, remove space from match.
   * e.g. tests/cisco_xr/admin_show_inventory/cisco_xr_admin_show_inventory.yml
      `vid: "V01 "`  ->     `vid: "V01"`

2022-04-11 19:21 UTC, jvanderaa commented on ntc_templates/templates/cisco_xr_admin_show_inventory.textfsm
> +  ^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s\S{3}\s+\d
I haven't looked at an XR in some time. Does this output also happen in a programatic interface with Netmiko/Napalm?

2022-05-22 18:56 UTC, jmcgill298 requested changes

2022-05-22 18:56 UTC, jmcgill298 commented on tests/cisco_xr/admin_show_inventory/cisco_xr_admin_show_inventory2.raw
> + PID: A9K-48X10GE-1G-TR      VID: V01                   SN: FOC2XXXXXX
```suggestion
 PID: A9K-48X10GE-1G-TR      VID: V01                   SN: FOC2XXXXXX
 
```

2023-03-29 08:32 UTC, andyb2000 commented
Hi, any movement on this?
I've tried to apply to mine for testing and it fails parsing. Example output from my "admin show inventory":

 Name: Rack 0                Descr: ASR-9010 Chassis
 PID: ASR-9010               VID: V01                   SN: FOX0000X0XX

 Name: 0/0                   Descr: 24X10G/1G  Service Edge Optimized LC
 PID: A9K-24X10GE-1G-SE      VID: V05                   SN: FOC0000XXXX

 Name: 0/7                   Descr: ASR 9000 8-port 100GE FLEXE SE linecard
 PID: A9K-8HG-FLEX-SE        VID: V02                   SN: FOC0000XXXX

And parsing fails:
Parsing errors
('State Error raised. Rule Line: 15. Input Line:  PID: ASR-9010               '
 'VID: V01                   SN: FOX0000X0XX')

(Differences to previous seem to be lacking quote marks and the spacing)

2023-06-02 10:17 UTC, diepes commented
@andyb2000 added you example as additional test.

2023-06-05 21:19 UTC, merged