Create cisco_ios_show_ap_summary.textfsm
networktocode/ntc-templates pull request #1155
Opened 2022-06-11 12:26 UTC by Rishabh4290

##### ISSUE TYPE

 - New Template Pull Request
 - Bugfix Pull Request
 - Additional Testing
 - Docs Pull Request

##### COMPONENT

##### SUMMARY

```

```

2022-07-26 15:41 UTC, agentggg commented
Hey there. I noticed the output does not clearly reflect the **show ap summary** command output on Cisco WLC. Any thoughts on how testing went or if it is a known issues, any thoughts on fixing this?

2022-12-21 23:08 UTC, jmcgill298 requested changes
Thanks @Rishabh4290 we will also need test files for this PR to be merged. Please see https://github.com/networktocode/ntc-templates/blob/master/docs/dev/dev_parser.md#tests

2022-12-21 23:08 UTC, jmcgill298 commented on ntc_templates/templates/cisco_ios_show_ap_summary.textfsm
> +  ^${AP_NAME}\s+${SLOT}\s+${AP_MODEL}\s+${MAC}\s+${RadioMac}\s+${LOCATION}\s+${COUNTRY}\s+${IP}\s+${State}$$ -> Record
```suggestion
  ^${AP_NAME}\s+${SLOT}\s+${AP_MODEL}\s+${MAC}\s+${RadioMac}\s+${LOCATION}\s+${COUNTRY}\s+${IP}\s+${State}\s*$$ -> Record
```

2022-12-21 23:08 UTC, jmcgill298 commented on ntc_templates/templates/cisco_ios_show_ap_summary.textfsm
> +  ^$$
```suggestion
```

2022-12-21 23:20 UTC, jmcgill298 commented
replaced by https://github.com/networktocode/ntc-templates/pull/1257

2022-12-21 23:20 UTC, closed without merging