added juniper show bgp summary
networktocode/ntc-templates pull request #1164
Opened 2022-06-24 17:10 UTC by ysanajong

##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
Juniper junos show bgp summary 

##### SUMMARY
Adds parsing for show bgp summary output on Juniper JunOS

2022-09-26 10:02 UTC, ysanajong commented
Can someone review this please?

2022-10-03 14:41 UTC, jvanderaa requested changes
Remove `EOF` that is not present on other templates.

2022-10-03 14:41 UTC, jvanderaa commented on ntc_templates/templates/juniper_junos_show_bgp_summary.textfsm
> +EOF
```suggestion

```

2024-07-15 22:32 UTC, jmcgill298 commented
replaced by https://github.com/networktocode/ntc-templates/pull/1744

2024-07-15 22:32 UTC, closed without merging