Updated support for Cisco NXOS devices
networktocode/ntc-templates pull request #1175
Opened 2022-07-29 02:10 UTC by ReK42

##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
- `show_ip_ospf_interface_brief`
- `show_ip_pim_rp_vrf`
- `show_ip_pim_neighbor_vrf`
- `show_ip_pim_interface_brief_vrf`
- `show_ip_pim_group-range_vrf`

##### SUMMARY
Added 5 new commands.

See tests for command output.

2022-07-29 02:59 UTC, ReK42 commented
There appears to be a problem with the Python 3.7 test environment, Travis is showing `The command "poetry install" failed`. Tests are passing for 3.6 and 3.8.

2022-08-07 17:57 UTC, jvanderaa commented
Restarted the build that failed still. 

Will continue to check on that, but also missing the `ERROR` statement.

2022-08-15 04:07 UTC, ReK42 commented
Looks like the environment is failing to be installed:

```
• Installing future (0.18.2): Installing...

  • Installing mccabe (0.6.1): Failed

  EnvCommandError

  Command ['/home/travis/virtualenv/python3.7.1/bin/pip', 'install', '--no-deps', '/home/travis/.cache/pypoetry/artifacts/c2/cd/ed/3c4495a1422fb12eefbca8b3c6ccc83ab4ec92fd39df029199cc4f4ee4/mccabe-0.6.1-py2.py3-none-any.whl'] errored with the following return code 1, and output: 

  Processing /home/travis/.cache/pypoetry/artifacts/c2/cd/ed/3c4495a1422fb12eefbca8b3c6ccc83ab4ec92fd39df029199cc4f4ee4/mccabe-0.6.1-py2.py3-none-any.whl

  Installing collected packages: mccabe

  ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/packaging-20.9.dist-info'
```

2023-04-11 13:22 UTC, pszulczewski requested changes
@ReK42 can you re-base this PR on master.
CI is now fixed.

2023-04-13 23:45 UTC, ReK42 commented
It looks like someone else added one of the commands in the meantime. I've removed that but kept the `show ip pim` commands. Note that due to the length of time since the original PR I no longer have an environment to test this in.

2023-04-14 15:05 UTC, pszulczewski requested changes
Please add `  ^. -> Error` at the end of each template so there is an error raised instead of an empty result and we are good to merge ;-)
Thank you!

2023-04-14 15:05 UTC, pszulczewski commented on ntc_templates/templates/cisco_nxos_show_ip_pim_group-range_vrf_all.textfsm
> +  ^\s*${GROUP_RANGE}\s+${ACTION}\s+${MODE}\s+${RP_ADDRESS}\s+${SHARED_TREE_RANGE}\s+${ORIGIN}\s*$$ -> Record
```suggestion
  ^\s*${GROUP_RANGE}\s+${ACTION}\s+${MODE}\s+${RP_ADDRESS}\s+${SHARED_TREE_RANGE}\s+${ORIGIN}\s*$$ -> Record
  ^. -> Error
 
```

2023-04-14 15:05 UTC, pszulczewski commented on ntc_templates/templates/cisco_nxos_show_ip_pim_interface_brief_vrf_all.textfsm
> +  ^\s*${INTERFACE}\s+${IP_ADDRESS}\s+${PIM_DR_ADDRESS}\s+${NEIGHBOR_COUNT}\s+${BORDER_INTERFACE}\s*$$ -> Record
```suggestion
  ^\s*${INTERFACE}\s+${IP_ADDRESS}\s+${PIM_DR_ADDRESS}\s+${NEIGHBOR_COUNT}\s+${BORDER_INTERFACE}\s*$$ -> Record
  ^. -> Error

```

2023-04-14 15:05 UTC, pszulczewski commented on ntc_templates/templates/cisco_nxos_show_ip_pim_neighbor_vrf_all.textfsm
> +  ^\s*${NEIGHBOR}\s+${INTERFACE}\s+${UPTIME}\s+${EXPIRES}\s+${DR_PRIORITY}\s+${BIDIR_CAPABLE}\s+${BFD_STATE}\s+${ECMP_REDIRECT_CAPABLE}\s*$$ -> Record
```suggestion
  ^\s*${NEIGHBOR}\s+${INTERFACE}\s+${UPTIME}\s+${EXPIRES}\s+${DR_PRIORITY}\s+${BIDIR_CAPABLE}\s+${BFD_STATE}\s+${ECMP_REDIRECT_CAPABLE}\s*$$ -> Record
  ^. -> Error

```

2023-04-14 15:05 UTC, pszulczewski commented on ntc_templates/templates/cisco_nxos_show_ip_pim_rp_vrf_all.textfsm
> +  ^\s*Auto-RP Discovery policy: ${AUTO_RP_DISCOVERY_POLICY}\s*$$ -> Record
```suggestion
  ^\s*Auto-RP Discovery policy: ${AUTO_RP_DISCOVERY_POLICY}\s*$$ -> Record
  ^. -> Error

```

2023-04-14 15:07 UTC, pszulczewski requested changes

2023-04-14 15:07 UTC, pszulczewski commented on ntc_templates/templates/cisco_nxos_show_ip_pim_group-range_vrf_all.textfsm
> +
```suggestion
  ^. -> Error

```

2023-04-14 15:09 UTC, pszulczewski approved these changes
OK looks like I was able to make the necessary changes myself.

Many thanks for your contribution and apologies that it took so long to merge it.

2023-04-14 15:15 UTC, merged