Add 5 new values to the 'cisco_ios_show_ip_bgp_summary.textfsm' template
networktocode/ntc-templates pull request #1433
Opened 2023-08-07 16:18 UTC by PavloSkliarenko

Added 5 new values to the template, which were previously skipped as unnecessary:
 - NEIGH_V
 - MSG_RCVD
 - MSG_SENT
 - TB_VER
 - IN_Q
 - OUT_Q

2023-08-08 12:59 UTC, jvanderaa requested changes
We are working on a data model normalization with more complete keys. I'd like to start with this PR, and if you want to also expand some of the other keys that were not being added for this PR, I would very much appreciate it. Major release coming within a week or so.

2023-08-08 12:59 UTC, jvanderaa commented on ntc_templates/templates/cisco_ios_show_ip_bgp_summary.textfsm
> +Value MSG_RCVD (\d+)
```suggestion
Value MESSAGES_RECIEVED (\d+)
```

2023-08-08 12:59 UTC, jvanderaa commented on ntc_templates/templates/cisco_ios_show_ip_bgp_summary.textfsm
> +Value OUT_Q (\d+)
```suggestion
Value MESSAGES_SENT (\d+)
Value TABLE_VER (\d+)
Value INPUT_QUEUE (\d+)
Value OUTPUT_QUEUE (\d+)
```

2023-08-09 13:11 UTC, PavloSkliarenko commented
Is now everything alright?

2023-08-14 09:29 UTC, PavloSkliarenko commented
>

2023-08-14 09:29 UTC, closed without merging