CiscoS300 'show system' template
networktocode/ntc-templates pull request #1521
Opened 2023-09-11 08:32 UTC by PavloSkliarenko

Template + test

2023-10-27 12:26 UTC, jvanderaa requested changes

2023-10-27 12:26 UTC, jvanderaa commented on ntc_templates/templates/cisco_s300_show_system.textfsm
> +Value ADDRESS (.*)
```suggestion
Value MAC_ADDRESS (.*)
```

2023-11-06 17:09 UTC, PavloSkliarenko commented
@jvanderaa How can I re-run tests, because they failed because of this [PR](https://github.com/networktocode/ntc-templates/pull/1557)?

2023-11-06 17:13 UTC, jvanderaa commented
Seeing if my latest re-run will get this.

2023-11-06 19:07 UTC, PavloSkliarenko commented
Fix value names according to new Data model

2023-11-08 13:53 UTC, merged