CiscoS300 'show interfaces description' template
networktocode/ntc-templates pull request #1525
Opened 2023-09-11 08:41 UTC by PavloSkliarenko

Template + test

2023-11-03 00:23 UTC, jvanderaa requested changes
Looking to update to the data model for interfaces.

2023-11-03 00:23 UTC, jvanderaa commented on ntc_templates/templates/cisco_s300_show_interfaces_description.textfsm
> +Value PORT (\S+)
```suggestion
Value INTERFACE (\S+)
```

2023-11-06 16:29 UTC, PavloSkliarenko commented
How can I re-run test, because they failed because of this [PR](https://github.com/networktocode/ntc-templates/pull/1557)?

2023-11-06 19:07 UTC, PavloSkliarenko commented
Fix value names according to new Data model

2023-11-07 00:57 UTC, jvanderaa approved these changes

2023-11-07 13:56 UTC, merged