Add Extreme platform with 6 templates
networktocode/ntc-templates pull request #1526
Opened 2023-09-11 08:48 UTC by PavloSkliarenko

New Extrem platform with the templates for 6 commands:

`show ipconfig`
`show ports description`
`show ports information`
`show ports information detail`
`show sharing`
`show vlan description`

2023-10-27 12:29 UTC, jvanderaa requested changes
Updates for the data model of 4.0

2023-10-27 12:29 UTC, jvanderaa commented on ntc_templates/templates/extreme_show_ports_description.textfsm
> +Value PORT (\d+)
```suggestion
Value INTERFACE (\d+)
```

2023-10-27 12:29 UTC, jvanderaa commented on ntc_templates/templates/extreme_show_ports_information.textfsm
> +Value PORT (\d+)
```suggestion
Value INTERFACE (\d+)
```

2023-10-27 12:29 UTC, jvanderaa commented on ntc_templates/templates/extreme_show_ports_information_detail.textfsm
> +Value PORT (\d+)
```suggestion
Value INTERFACE (\d+)
```

2023-10-27 12:29 UTC, jvanderaa commented on ntc_templates/templates/extreme_show_vlan_description.textfsm
> +Value ID (\d+)
```suggestion
Value VLAN_NAME (\S+)
Value VLAN_ID (\d+)
```

2023-11-06 13:41 UTC, jvanderaa approved these changes

2023-11-06 13:41 UTC, merged

2023-12-04 21:59 UTC, mayafox commented
This does not correctly identify the OS of the Extreme device in use.
Is this Extreme TierraOS? VOSS? XOS? NOS? SLXOS? Wing?

2023-12-05 07:30 UTC, PavloSkliarenko commented
@mayafox This is ExtremeXOS (EXOS)

2023-12-05 16:33 UTC, mayafox commented
> @mayafox This is ExtremeXOS (EXOS)

If that's the case, the file names of the templates and test files should  reflect that 
The file name format  is <mfg>_<platform>_<underscored command> 
for example, the show ports description command  it would be  extreme_exos_show_ports_description.textfsm

This allows the NTC code templates and textfsm  to differentiate between the platforms from the same mfg that have different output formats for the same command.

2023-12-12 07:59 UTC, PavloSkliarenko commented
@mayafox Fix platform name  in this [PR](https://github.com/networktocode/ntc-templates/pull/1576)