Issue 1556 proposed fix
networktocode/ntc-templates pull request #1562
Opened 2023-11-16 18:54 UTC by collin-wicker

Updated juniper_junos_show_chassis_hardware.textfsm and associated test files as proposed fix for issue 1556. With the updates the parsed output contains all item numbers, version number, part numbers, serial numbers, and description for each item listed in the test file command output.

2023-11-17 15:05 UTC, jvanderaa requested changes
Looking good, just looking to be a bit more explicit on a few things as we chatted some.

2023-11-17 15:05 UTC, jvanderaa commented on ntc_templates/templates/juniper_junos_show_chassis_hardware.textfsm
> +Value CHASSIS_SN (\w+)
```suggestion
Value CHASSIS_SERIAL_NUMBER (\w+)
```

2023-11-17 15:05 UTC, jvanderaa commented on ntc_templates/templates/juniper_junos_show_chassis_hardware.textfsm
> +Value CHASSIS_DESC (.*)
```suggestion
Value CHASSIS_DESCRIPTION (.*)
```

2023-11-20 16:31 UTC, collin-wicker commented
I have unabbreviated the value names as requested to make the results more explicit. Please review the latest commit for these changes.

2023-11-20 17:52 UTC, collin-wicker commented
Tests have failed because I forgot to update the names in the test files. I will update the test files and commit.

2024-02-22 17:02 UTC, jvanderaa approved these changes

2024-02-22 17:05 UTC, merged