New templates: alcatel_sros_ping.textfsm and alcatel_sros_ping_rapid.textfsm
networktocode/ntc-templates pull request #1615
Opened 2024-02-15 01:30 UTC by jorlandobr

Added template ands test for Alcatel (Nokia) SROS for the "ping" and "ping rapid" commands. Index updated

2024-02-19 20:50 UTC, jorlandobr commented
> Added template ands test for Alcatel (Nokia) SROS for the **"ping"**, **"ping rapid"** and **"show service id interface"** commands. Index updated.
> 
> Modified **"show service sap using"** changing the value **INGRESS_QOS** from digit to string to avoid errors when trucated rows present the ***** character.

Modified the ping template, so a single template works with "ping" and "ping rapid" commands.

2024-03-27 21:24 UTC, jvanderaa requested changes
Please update to full names.

2024-03-27 21:24 UTC, jvanderaa commented on ntc_templates/templates/alcatel_sros_show_service_id_interface.textfsm
> +Value IFACE_NAME (\S+)
```suggestion
Value INTERFACE_NAME (\S+)
```

2024-03-27 21:24 UTC, jvanderaa commented on ntc_templates/templates/alcatel_sros_show_service_id_interface.textfsm
> +Value IFACE_QTY (\d+)
```suggestion
Value INTERFACE_QTY (\d+)
```

2024-03-27 23:07 UTC, jorlandobr commented on ntc_templates/templates/alcatel_sros_show_service_id_interface.textfsm
> +Value IFACE_NAME (\S+)
Changes applied.

2024-03-27 23:07 UTC, jorlandobr commented on ntc_templates/templates/alcatel_sros_show_service_id_interface.textfsm
> +Value IFACE_QTY (\d+)
Changes applied.

2024-04-11 15:01 UTC, jorlandobr reviewed
Changes made as requested

2024-04-24 13:42 UTC, jmcgill298 requested changes
Thanks for the PR, just a couple of small changes requested

2024-04-24 13:42 UTC, jmcgill298 commented on ntc_templates/templates/alcatel_sros_show_service_id_interface.textfsm
> +  ^Interfaces -> Done
```suggestion
  ^Interfaces\s*:\s+\d+\s*$$
```

We are at the end of the data, so I don't see a need to move to another state to move to the implicit `End -> Record` state.

2024-04-24 13:42 UTC, jmcgill298 commented on ntc_templates/templates/alcatel_sros_show_service_sap-using.textfsm
> +  ^\S+
What is the reason for this change? Can you update the test case or add a test case with data the exemplifies the issue this is fixing?

2024-04-24 18:01 UTC, jmcgill298 commented on ntc_templates/templates/alcatel_sros_show_service_sap-using.textfsm
> +  # added to avoid errors with trucated values alert message
Is this referring to `* indicates that the corresponding row element may have been truncated.`?

2024-07-03 22:44 UTC, jmcgill298 commented
Did not hear back on questions, so replaced with https://github.com/networktocode/ntc-templates/pull/1729

2024-07-03 22:44 UTC, closed without merging