Add support for the Huawei OLT display version command. Command + Tests
networktocode/ntc-templates pull request #1627
Opened 2024-02-28 15:45 UTC by evilmonkey19

It adds supports as suggested in the issue #1624. This is the first command.

*display version*

2024-03-07 11:17 UTC, evilmonkey19 commented
The pull request is ready for the code review! Thanks for the help :)

2024-03-07 16:29 UTC, evilmonkey19 commented
Okey, now it is already tested on a real Huawei smartax and it works. Sorry for all the commits ✅

2024-03-08 13:27 UTC, jvanderaa requested changes
Just looking to convert `SN` to `SERIAL` for cross vendor capability.

2024-03-08 13:27 UTC, jvanderaa commented on ntc_templates/templates/huawei_smartax_display_ont_info_by-sn_sn.textfsm
> +Value SN (\w+\s*\(*\S*\))
```suggestion
Value SERIAL (\w+\s*\(*\S*\))
```

2024-03-08 13:27 UTC, jvanderaa commented on ntc_templates/templates/huawei_smartax_display_ont_info_fsp.textfsm
> +Value SN (\w+)
```suggestion
Value SERIAL (\w+)
```

2024-03-08 13:27 UTC, jvanderaa commented on ntc_templates/templates/huawei_smartax_display_ont_info_summary_sn.textfsm
> +Value SN (\w+)
```suggestion
Value SERIAL (\w+)
```

2024-03-08 13:34 UTC, jvanderaa commented on ntc_templates/templates/huawei_smartax_display_ont_info_by-sn_sn.textfsm
> +Value SN (\w+\s*\(*\S*\))
```suggestion
Value SERIAL_NUMBER (\w+\s*\(*\S*\))
```

2024-03-08 13:45 UTC, evilmonkey19 commented
> Just looking to convert `SN` to `SERIAL` for cross vendor capability.

Done 👍

2024-03-12 09:12 UTC, evilmonkey19 commented
There was a really small bug in the tests due to the change of SERIAL_NUMBER. Now it is completely fixed :)

2024-03-19 09:39 UTC, evilmonkey19 commented
I close this pull-request as I have done new pull-requests spliting the commands as suggested by @jvanderaa. Thanks for the help!

2024-03-19 09:39 UTC, closed without merging