New 'show vlans' template for cisco_ios
networktocode/ntc-templates pull request #1631
Opened 2024-03-08 17:02 UTC by chadell

2024-03-08 17:05 UTC, jvanderaa approved these changes

2024-03-08 17:27 UTC, jmcgill298 requested changes
This will need to be updated to follow our standard for matching all lines and including an `-> Error` statement

2024-03-08 17:28 UTC, chadell commented
@jvanderaa I have a problem with the `test_index_ordering`.
As the index is in my PR, the parsing works, but if I swap the with the `show vlan` then the `show vlans` command uses the `show vlan` one, I guess because it's matching the string.

2024-03-11 16:27 UTC, jmcgill298 approved these changes

2024-03-11 16:27 UTC, merged