Update template: huawei_smartax display_ont_info_fsp to display_ont_info_0_0_0
networktocode/ntc-templates pull request #1711
Opened 2024-06-06 10:42 UTC by evilmonkey19

Currently, there is a little problem with the template. In the Huawei SmartAX models instead of using the 0/0/0 for example, the syntax is `display ont info 0 0 0`. I have changed so it matches the exact command as the one you would send via Netmiko. Also I have updated the template because if you have an output like the following it would have crashed:
```
  -----------------------------------------------------------------------------
  F/S/P   ONT         SN         Control     Run      Config   Match    Protect
          ID                     flag        state    state    state    side
  -----------------------------------------------------------------------------
    0/ 0/0    0  NEBW3W2ABK434A01  active      -        -        -        yes
    0/ 0/0    1  NFNCFTKLQNERTWPT  active      -        -        -        yes
  -----------------------------------------------------------------------------
  F/S/P   ONT-ID   Description
  -----------------------------------------------------------------------------
  0/ 0/0       0   The equable treatment pushes.
  0/ 0/0       1   The vacuous statistic attaches.
  -----------------------------------------------------------------------------
  In port 0/ 0/0, the total number of ONTs are: 2, online: 0, offline: 0
  -----------------------------------------------------------------------------
  ```
  
  Also an extra test case has been added.

2024-06-06 11:00 UTC, itdependsnetworks commented
is it possible it would be something like `display ont info 1 2 0` ?

2024-06-06 14:27 UTC, evilmonkey19 commented
Yees, you can running using something like `display ont info 0 0 1` or `display ont info 1 2 0`. The 0 0 0 it's just a name. In the index I use the (\d+\s\d+\s\d+) to catch the  1 2 0.

2024-07-04 16:46 UTC, evilmonkey19 commented
Hey! How is it going the review?

2024-07-22 22:45 UTC, jmcgill298 requested changes

2024-07-22 22:45 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_0_0/huawei_smartax_display_ont_info_fsp_3.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-22 22:45 UTC, jmcgill298 commented on ntc_templates/templates/index
> +huawei_smartax_display_ont_info_0_0_0.textfsm:huawei_smartax_display_ont_info_description.textfsm, .*, huawei_smartax, di[[splay]] ont i[[nfo]] (\d+\s\d+\s\d+) *$
```suggestion
huawei_smartax_display_ont_info_0_0_0.textfsm:huawei_smartax_display_ont_info_description.textfsm, .*, huawei_smartax, di[[splay]] ont i[[nfo]] (\d+\s\d+\s\d+)\s*$
```

2024-07-22 22:46 UTC, jmcgill298 approved these changes

2024-07-23 00:04 UTC, jmcgill298 commented
@evilmonkey19 is this different than https://github.com/networktocode/ntc-templates/blob/master/ntc_templates/templates/huawei_smartax_display_ont_info_0_1_2.textfsm ?

If so, something needs to change with the regex in the index file

2024-07-24 10:41 UTC, closed without merging