Updated templates: huawei_smartax_display_ont_info
networktocode/ntc-templates pull request #1715
Opened 2024-06-13 10:45 UTC by evilmonkey19

Hi!

I have modified the templates related to Huawei SmartAX for `display ont info`. Although this command seems easy depending on the args afterwards can match one or the other now. For instead `display ont info 0 1 2` gives the input that is a list. However `display ont info 0 1 2 3` gives the specific information for just one ONT.

List commands examples:

- `display ont info 0 1 2`
- `display ont info 0` (interface gpon 0/0 mode)

Specific commands examples:

- `display ont info 0 1 2 3`
- `display ont info by-sn ABCDEFG1234`
- `display ont info 0 1` (interface gpon 0/0 mode)

2024-07-05 20:47 UTC, jmcgill298 requested changes

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1.textfsm
> +  ^\s*- -> Next
```suggestion
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1.textfsm
> +  ^\s*- -> Next
```suggestion
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1.textfsm
> +  ^\s*- -> Next
```suggestion
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1.textfsm
> +  ^\s*- -> Next
```suggestion
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1.textfsm
> +  ^\s*<T-CONT\s*${T_CONT}>\s*DBA\s*Profile-ID\s*:\s*\d+$$ -> Next
```suggestion
  ^\s*<T-CONT\s*${T_CONT}>\s*DBA\s*Profile-ID\s*:\s*\d+$$
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1.textfsm
> +  ^\s*<T-CONT\s*${T_CONT}>\s*DBA\s*Profile-ID\s*:\s*\d+$$ -> Next
Next is the default behavior, so it does not need to be specified

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1.textfsm
> +  ^\s*TR069\s+server\s+profile\s+name\s*:\s*${TR069_SERVER_PROFILE_NAME}
```suggestion
  ^\s*TR069\s+server\s+profile\s+name\s*:\s*${TR069_SERVER_PROFILE_NAME}

```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1_2.textfsm
> +  ^. -> Error
```suggestion
  ^. -> Error

```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_0_1_2.textfsm
> +  ^\s+ID\s+flag\s+state\s+state\s+state\s+side -> SNs
```suggestion
  ^\s+ID\s+flag\s+state\s+state\s+state\s+side -> SNs
  ^. -> Error
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_3.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1/huawei_smartax_display_ont_info_1.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_3.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2_3/huawei_smartax_display_ont_info_1.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2_3/huawei_smartax_display_ont_info_2.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_by-sn_ABC/huawei_smartax_display_ont_info_1.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_by-sn_ABC/huawei_smartax_display_ont_info_2.raw
> +  -----------------------------------------------------------------------------
```suggestion
  -----------------------------------------------------------------------------

```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The acrid shallot extends.     "
```suggestion
    description: "The acrid shallot extends."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The gusty sari coordinates.    "
```suggestion
    description: "The gusty sari coordinates."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The lavish gun strengthens.    "
```suggestion
    description: "The lavish gun strengthens."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The rotten census sounds.      "
```suggestion
    description: "The rotten census sounds."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The fanatical twine finances.  "
```suggestion
    description: "The fanatical twine finances."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The brawny honeydew deserts.   "
```suggestion
    description: "The brawny honeydew deserts."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The ancient hunter reinforces. "
```suggestion
    description: "The ancient hunter reinforces."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The deranged echidna glues.    "
```suggestion
    description: "The deranged echidna glues."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The wandering elf assists.     "
```suggestion
    description: "The wandering elf assists."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The industrious bumper kicks.  "
```suggestion
    description: "The industrious bumper kicks."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The macho quart blinks.        "
```suggestion
    description: "The macho quart blinks."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0_1_2/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The damaging nerve nests.      "
```suggestion
    description: "The damaging nerve nests."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The acrid shallot extends.     "
```suggestion
    description: "The acrid shallot extends."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The gusty sari coordinates.    "
```suggestion
    description: "The gusty sari coordinates."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The lavish gun strengthens.    "
```suggestion
    description: "The lavish gun strengthens."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The rotten census sounds.      "
```suggestion
    description: "The rotten census sounds."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The fanatical twine finances.  "
```suggestion
    description: "The fanatical twine finances."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The brawny honeydew deserts.   "
```suggestion
    description: "The brawny honeydew deserts."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The ancient hunter reinforces. "
```suggestion
    description: "The ancient hunter reinforces."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The deranged echidna glues.    "
```suggestion
    description: "The deranged echidna glues."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The wandering elf assists.     "
```suggestion
    description: "The wandering elf assists."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The industrious bumper kicks.  "
```suggestion
    description: "The industrious bumper kicks."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The macho quart blinks.        "
```suggestion
    description: "The macho quart blinks."
```

2024-07-05 20:47 UTC, jmcgill298 commented on tests/huawei_smartax/display_ont_info_0/huawei_smartax_display_ont_info_fsp_2.yml
> +    description: "The damaging nerve nests.      "
```suggestion
    description: "The damaging nerve nests."
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_description.textfsm
> +Value DESCRIPTION (.+)
```suggestion
Value DESCRIPTION (.+?)
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_description.textfsm
>    ^\s+${FSP}\s+${ONT_ID}\s+${DESCRIPTION} -> Record
```suggestion
  ^\s+${FSP}\s+${ONT_ID}\s+${DESCRIPTION}\s*$$ -> Record
```

2024-07-05 20:47 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_description.textfsm
>    ^\s+${FSP}\s+${ONT_ID}\s+${DESCRIPTION} -> Record
Need to ignore trailing whitespace

2024-07-15 13:28 UTC, evilmonkey19 reviewed
I just checked all the changes are everything is passing 👍  Thanks for the suggestions 😄

2024-07-15 15:25 UTC, jmcgill298 commented on ntc_templates/templates/huawei_smartax_display_ont_info_description.textfsm
>    ^\s+${FSP}\s+${ONT_ID}\s+${DESCRIPTION} -> Record
@evilmonkey19 I don't think this suggestion made it in to your updates. Also, it looks like there is a conflict that needs to be addressed

2024-07-16 14:10 UTC, jmcgill298 commented
@evilmonkey19 I went ahead and rebased for you and merged this in https://github.com/networktocode/ntc-templates/pull/1743

2024-07-16 14:10 UTC, closed without merging