New template: cisco_ios_show_power_inline.textfsm
networktocode/ntc-templates pull request #1881
Opened 2024-10-17 12:19 UTC by JKLs12

Added new cisco template cisco_ios_show_power_inline.textfsm for PoE status

2024-10-17 13:59 UTC, jmcgill298 commented on ntc_templates/templates/cisco_ios_show_power_inline.textfsm
> +  ^. -> Error
```suggestion
  ^. -> Error

```

2024-10-17 14:01 UTC, jmcgill298 approved these changes

2024-10-17 14:28 UTC, jmcgill298 commented
@JKLs12 there are helper files to clean up yaml files: https://ntc-templates.readthedocs.io/en/latest/dev/dev_environment/#cli-helper-commands

2024-10-17 15:36 UTC, jmcgill298 requested changes

2024-10-17 15:36 UTC, jmcgill298 commented on ntc_templates/templates/cisco_ios_show_power_inline.textfsm
> +Value Max (\d+\.\d+)
```suggestion
Value INTERFACE (\S+)
Value ADMIN_STATUS (\S+)
Value OPERATIONAL_STATUS (on|off)
Value POWER (\d+\.\d+)
Value DEVICE (\S+(\s\S+)*)
Value CLASS (\d|n/a)
Value MAX (\d+\.\d+)

```
We standardize on using all caps for capture group names for ease of identifying, and started standardizing some of the names across all templates

2024-10-17 15:36 UTC, jmcgill298 commented on ntc_templates/templates/cisco_ios_show_power_inline.textfsm
> +  ^\s*${Interface}\s+${Admin}\s+${Oper}\s+${Power}\s+${Device}\s+${Class}\s+${Max}\s*$$ -> Record
```suggestion
  ^\s*${INTERFACE}\s+${ADMIN_STATUS}\s+${OPERATIONAL_STATUS}\s+${POWER}\s+${DEVICE}\s+${CLASS}\s+${MAX}\s*$$ -> Record

```

2024-10-17 15:36 UTC, jmcgill298 commented on tests/cisco_ios/show_power_inline/cisco_ios_show_power_inline.raw
> +Gi1/0/24  auto   off        0.0     n/a                 n/a   30.0
```suggestion
```

2024-10-17 15:36 UTC, jmcgill298 commented on tests/cisco_ios/show_power_inline/cisco_ios_show_power_inline.raw
> +Gi1/0/9   auto   on         30.0    AIR-AP1562I-E-K9    4     30.0
```suggestion
```
There is a lot of duplicate type data, just trim it down for ease of updating

2024-10-17 15:36 UTC, jmcgill298 commented on tests/cisco_ios/show_power_inline/cisco_ios_show_power_inline.yml
> +  Power: "0.0"
```suggestion
parsed_sample:
- admin_status: "auto"
  class: "4"
  device: "AIR-AP1562I-E-K9"
  interface: "Gi1/0/1"
  max: "30.0"
  operational_status: "on"
  power: "30.0"
- admin_status: "auto"
  class: "4"
  device: "AIR-AP1562I-E-K9"
  interface: "Gi1/0/2"
  max: "30.0"
  operational_status: "on"
  power: "30.0"
- admin_status: "auto"
  class: "4"
  device: "AIR-AP1562I-E-K9"
  interface: "Gi1/0/3"
  max: "30.0"
  operational_status: "on"
  power: "30.0"
- admin_status: "auto"
  class: "4"
  device: "C9120AXE-E"
  interface: "Gi1/0/10"
  max: "30.0"
  operational_status: "on"
  power: "23.2"
- admin_status: "auto"
  class: "4"
  device: "AIR-AP1562I-E-K9"
  interface: "Gi1/0/11"
  max: "30.0"
  operational_status: "on"
  power: "30.0"
- admin_status: "auto"
  class: "n/a"
  device: "n/a"
  interface: "Gi1/0/12"
  max: "30.0"
  operational_status: "off"
  power: "0.0"
- admin_status: "auto"
  class: "n/a"
  device: "n/a"
  interface: "Gi1/0/13"
  max: "30.0"
  operational_status: "off"
  power: "0.0"
```

ntc-templates will convert all capture groups to lowercase

2024-10-18 07:20 UTC, JKLs12 commented
@jmcgill298 Thanks for your help and patience :)

2024-10-18 14:55 UTC, jmcgill298 approved these changes

2024-10-18 15:01 UTC, merged