support for case of unassigned ipv6 address as chassis ID
networktocode/ntc-templates pull request #1887
Opened 2024-10-28 20:21 UTC by mcn29

The CHASSIS_ID value :: is shown by IOS XE when the remote device uses its IPv6 address as the chassis ID but has no address assigned.

This change prevents the template from throwing an error as soon as it encounters the : character

2024-10-28 20:25 UTC, jmcgill298 requested changes
Thanks @mcn29 , just a couple of minor changes

2024-10-28 20:25 UTC, jmcgill298 commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.raw
> +    Location - not advertised
```suggestion
    Location - not advertised

```

2024-10-28 20:25 UTC, jmcgill298 commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +VLAN_ID: '999'
```suggestion
VLAN_ID: '999'

```

2024-10-28 20:25 UTC, jmcgill298 commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +CAPABILITIES: T
ntc_templates will convert these to lowercase, so these will need to be updated to be lowercase.

2024-10-28 23:49 UTC, mjbear commented
resolves #1884

2024-10-29 00:08 UTC, mjbear requested changes

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +NEIGHBOR_INTERFACE: SW PORT
```suggestion
neighbor_interface: "SW PORT"
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +NEIGHBOR_NAME: SEPaabbccddeeff.phones.company.domain
```suggestion
neighbor_name: "SEPaabbccddeeff.phones.company.domain"
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +NEIGHBOR_PORT_ID: aabbccddeeff:P1
```suggestion
neighbor_port_id: "aabbccddeeff:P1"
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +PLATFORM: CP-6901
```suggestion
platform: "CP-6901"
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +POWER_CLASS: ''
```suggestion
power_class: ""
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +POWER_DEVICE_TYPE: ''
```suggestion
power_device_type: ""
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +CHASSIS_ID: "::"
```suggestion
chassis_id: "::"
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +POWER_PAIR: ''
```suggestion
power_pair: ""
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +POWER_PRIORITY: ''
```suggestion
power_priority: ""
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +POWER_REQUESTED: ''
```suggestion
power_requested: ""
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +POWER_SOURCE: ''
```suggestion
power_source: ""
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +SERIAL: FCH12345GVM
```suggestion
serial: "FCH12345GVM"
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +SW_REVISION: SCCP6901.9-3-1-SR2-2
```suggestion
sw_revision: "SCCP6901.9-3-1-SR2-2"
```

2024-10-29 00:08 UTC, mjbear commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +VLAN_ID: '999'
```suggestion
vlan_id: "999"
```

2024-10-29 12:50 UTC, mcn29 commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
Ok, thanks for the suggestions. I'll bear the point in mind in the next PRs.

2024-10-29 13:14 UTC, jmcgill298 approved these changes

2024-10-29 13:26 UTC, jmcgill298 commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +vlan_id: "999"
```suggestion
---
parsed_sample:
  capabilities: "T"
  chassis_id: "::"
  fw_revision: "6901.0-0-0-01-05"
  hw_revision: "1.0"
  local_interface: "Gi1/0/22"
  mac_address: "aabb.ccdd.eeff"
  manufacturer: "Cisco Systems, Inc."
  mgmt_address: "10.20.30.40"
  neighbor_description: "Cisco IP Phone 6901,SCCP6901.9-3-1-SR2-2"
  neighbor_interface: "SW PORT"
  neighbor_name: "SEPaabbccddeeff.phones.company.domain"
  neighbor_port_id: "aabbccddeeff:P1"
  platform: "CP-6901"
  power_class: ""
  power_device_type: ""
  power_pair: ""
  power_priority: ""
  power_requested: ""
  power_source: ""
  serial: "FCH12345GVM"
  sw_revision: "SCCP6901.9-3-1-SR2-2"
  vlan_id: "999"
```

2024-10-29 13:34 UTC, jmcgill298 commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +  vlan_id: "999"
```suggestion
  - capabilities: "T"
    chassis_id: "::"
    fw_revision: "6901.0-0-0-01-05"
    hw_revision: "1.0"
    local_interface: "Gi1/0/22"
   mac_address: "aabb.ccdd.eeff"
    manufacturer: "Cisco Systems, Inc."
    mgmt_address: "10.20.30.40"
    neighbor_description: "Cisco IP Phone 6901,SCCP6901.9-3-1-SR2-2"
    neighbor_interface: "SW PORT"
    neighbor_name: "SEPaabbccddeeff.phones.company.domain"
    neighbor_port_id: "aabbccddeeff:P1"
    platform: "CP-6901"
    power_class: ""
    power_device_type: ""
    power_pair: ""
    power_priority: ""
    power_requested: ""
    power_source: ""
    serial: "FCH12345GVM"
    sw_revision: "SCCP6901.9-3-1-SR2-2"
    vlan_id: "999"
```

2024-10-29 13:39 UTC, jmcgill298 commented on tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail6.yml
> +    mgmt_address: "10.20.30.40"
```suggestion
    mac_address: "aabb.ccdd.eeff"
    manufacturer: "Cisco Systems, Inc."
    mgmt_address: "10.20.30.40"
```

2024-10-29 14:03 UTC, merged

2024-10-30 14:42 UTC, mjbear commented
Thank you @jmcgill298! :fireworks: