Adding new template for Alcatel aos: `show system`
networktocode/ntc-templates pull request #1900
Opened 2024-11-18 15:11 UTC by evilmonkey19

2024-11-18 22:47 UTC, mjbear commented
@evilmonkey19
This PR also has multiple template changes.

2024-11-19 09:10 UTC, evilmonkey19 commented
Fixed ✅ It was not intended but rather that i'm doing local development.

2024-11-20 02:18 UTC, mjbear commented on ntc_templates/templates/index
> +alcatel_aos_show_system.textfsm, .*, alcatel_aos, show system
Does the AOS command line support any shorthand for `show system`?

2024-11-20 02:31 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +Value Service (\d+)
```suggestion
Value SERVICES (\d+)
```

Make plural to match raw output.
Capitalize capture group name.

2024-11-20 02:38 UTC, mjbear requested changes

2024-11-20 02:38 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +Value LOCATION ([^,]+)
```suggestion
Value DESCRIPTION (.+)
Value OBJECT_ID (.+)
Value UP_TIME (.+)
Value CONTACT (.+)
Value NAME (.+)
Value LOCATION (.+)
```

Simplify regexes.
Simpler and flexible should mean less breakage over time.

2024-11-20 02:38 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +Value COMMENTS ([^,]+)
```suggestion
Value COMMENTS (.+)
```

Simplify regex.

2024-11-20 02:38 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +Value DATE_TIME (\S+\s*\S+\s*\d+\s*\d+\s*\d+:\d+:\d+\s*(\(\w+\)))
```suggestion
Value DATE_TIME ((\S+\s*)+)
```

Simplify regex.

Fortunately you can (and are) anchoring the match line with that trailing comma. :grinning:

2024-11-20 02:40 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +Value Service (\d+)
If this suggestion (and others) help, click the button here to accept them. Thank you!

2024-11-20 02:49 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +Value UP_TIME (\d+ days \d+ hours \d+ minutes and \d+ seconds)
```suggestion
Value UPTIME (.+)
```

Move `UP_TIME` to `UPTIME` as that is a common capture group name. (We're hoping to standardize/normalize where we can.)

2024-11-20 02:50 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +  ^\s*Up\s*Time:\s*${UP_TIME},$$
```suggestion
  ^\s*Up\s*Time:\s*${UPTIME},$$
```

Match capture group change (as noted above in the file) to the common occurrence.

2024-11-20 02:51 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +  ^\s*Services:\s*${Service},$$
```suggestion
  ^\s*Services:\s*${SERVICES},$$
```

Change capture group name and make all uppercase.

2024-11-20 02:52 UTC, mjbear commented on ntc_templates/templates/alcatel_aos_show_system.textfsm
> +Value UP_TIME (\d+ days \d+ hours \d+ minutes and \d+ seconds)
https://github.com/networktocode/ntc-templates/blob/master/docs/dev/data_model.md

2024-11-20 09:53 UTC, evilmonkey19 commented
I added all your suggestions 😀 Thanks again! I added also the short-handed version

2024-11-20 12:07 UTC, mjbear commented
> I added all your suggestions 😀 Thanks again! I added also the short-handed version

@evilmonkey19
Nice!

Was the [Commit suggestion button](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) available?
Based on the commit history it doesn't seem like it.
For local development, when you accept changes from GH, you'd run a `git pull` to pull down changes to be up-to-date on your local system.

![Commit suggestion button](https://github.com/user-attachments/assets/568315cd-e5b9-4049-a6cf-405bff4e0a5f)

2024-11-20 12:46 UTC, evilmonkey19 commented
Yees it was available hehe. Simply just that sometimes i like to do things manually as everthing is automated :P

2024-11-20 12:51 UTC, mjbear commented
> Yees it was available hehe. Simply just that sometimes i like to do things manually as everthing is automated :P

Darn.
We co-authored on this one and now it doesn't show it. :disappointed:

2024-11-22 13:11 UTC, evilmonkey19 commented
Is there anything i could do to add you?

2024-11-22 14:24 UTC, mjbear commented
> Is there anything i could do to add you? Simply add a space or something similar and i add it :)

I'll see if there's anything else, but for now things appear to be fairly complete on this PR.
Though I did come up with a documentation idea.

If you were to add co-author text to the PR description (it might get picked up).
For example, GH auto-added similar text at [this previous commit for another PR](https://github.com/networktocode/ntc-templates/commit/c18104e983a60b5f7a7461def798fb84ab3e0d61).

```
Co-authored-by: Michael Bear <38406045+mjbear@users.noreply.github.com>
```

2024-11-25 19:54 UTC, jmcgill298 approved these changes

2024-11-25 19:57 UTC, jmcgill298 approved these changes

2024-11-25 20:11 UTC, merged