New template Alcatel AOS: `show mac-address-table`
networktocode/ntc-templates pull request #1902
Opened 2024-11-19 09:55 UTC by evilmonkey19

2024-11-19 10:26 UTC, evilmonkey19 commented
Added support for R8 version where the command is `show mac-learning`. In the R6 version the command is `show mac-address-table`. I wanted to combine both commands to simplify everything as Alcatel decided to make it difficult :)

2024-11-20 16:30 UTC, jmcgill298 requested changes
just one adjustment @evilmonkey19

2024-11-20 16:30 UTC, jmcgill298 commented on ntc_templates/templates/alcatel_aos_show_mac-address-table.textfsm
> +  ^\s*------------+----------------------+-------------------+------------------+-------------+-------------------------\s*$$
```suggestion
  ^\s*-+\+
  ^\s*${VLAN_ID}\s*${MAC}\s*${TYPE}\s*(---|${PROTOCOL})\s*${OPERATION}\s*${INTERFACE}\s*$$ -> Record
  ^\s*Domain\s*Vlan\/SrvcId\[ISId\/vnId\]\s*Mac\s*Address\s*Type\s*Operation\s*Interface\s*$$
```

I feel comfortable that we are only matching table dividers with looking for lines that have `-` repeated followed by a `+`

2024-11-22 15:15 UTC, mjbear commented
> @evilmonkey19 I'd be glad to submit further suggestions if you're willing to accept them via GitHub workflow (Commit Suggestion). Thank you! 🙂

@evilmonkey19 
I'm having issues trying to compare a branch on my fork to a branch on your fork.
Would you please sync your fork's `master` branch as an attempt to fix this?

2024-11-25 10:39 UTC, evilmonkey19 commented
I synced the fork :)

2024-11-25 14:08 UTC, mjbear commented
> I synced the fork now :)

Thank you.
Hmm, GitHub still doesn't want to show me your fork in order for me to submit a PR against your fork.

Oh well, I can work off of the code review page as we've been doing.
Thank you for collaborating with me! :grin:

2024-11-25 19:56 UTC, jmcgill298 commented on ntc_templates/templates/alcatel_aos_show_mac-address-table.textfsm
> +  ^\s*
```suggestion
  ^\s*$$
```

2024-11-27 21:06 UTC, jmcgill298 commented on ntc_templates/templates/alcatel_aos_show_mac-address-table.textfsm
> +  ^\s*
```suggestion
  ^Legend
  ^\s+Mac\s+Address:
```
we don't want to catch every line that starts with a space, as that would catch about every line, and negate the point of the catchall/error line.

2024-11-27 21:09 UTC, jmcgill298 approved these changes

2024-11-27 21:14 UTC, merged