Add Fsas Si-R show system information template
networktocode/ntc-templates pull request #1956
Opened 2024-12-31 16:42 UTC by caribouHY

2025-01-01 00:44 UTC, mjbear commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +Value VERSION (\d\d.\d\d)
Simplify the numeric part of the VERSION capture group.
Escape the period since we want a literal period.

```suggestion
Value VERSION (\d+\.\d+)
```

2025-01-01 00:46 UTC, mjbear commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +Value CONFIG_FILE (config\d)
I'm on the fence whether it's better to just match these two with a simpler regex.

Which way do you lean on the topic?

2025-01-01 00:47 UTC, mjbear commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +Value FIRMWARE2_VERSION (\d\d.\d\d)
Similar to `FIRMWARE` above, simplify the version capture group regexes.

```suggestion
Value FIRMWARE1_VERSION (\d+\.\d+)
Value FIRMWARE2_VERSION (\d+\.\d+)
```

2025-01-01 00:52 UTC, mjbear commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +  ^Security Software Ver.\s+:\s+.+$$
Match whitespace with regexes just in case the spacing ever changes. Flexibility should keep the care-and-feeding of the template to a minimum in the long run.

Escape certain period characters to match literal periods.

```suggestion
  ^Serial\s+No\.\s+:\s+${SERIAL}\s*$$
  ^ROM\s+Ver\.\s+:\s+.+$$
  ^Firm\s+Ver\.\s+:\s+V${VERSION}\s*.+$$
  ^Running-firmware\s+:\s+${FIRMWARE}\s*$$
  ^Firmware1\s+Ver\.\s+:\s+V${FIRMWARE1_VERSION}\s*.+$$
  ^Firmware2\s+Ver\.\s+:\s+V${FIRMWARE2_VERSION}\s*.+$$
  ^Security\s+Software\s+Ver\.\s+:\s+.+$$
```

2025-01-01 00:57 UTC, mjbear commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +  ^WWAN\d?\s+.+$$
@caribouHY
Do you have test output that covers `USB` (and WWAN) followed by a number?

The question and goal is to have good test coverage. Thank you!

2025-01-01 03:36 UTC, caribouHY commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +Value CONFIG_FILE (config\d)
I think that FIRMWARE and CONFIG name may change in the future.
I fixed the regex.
 ```
 Value FIRMWARE (\S+)
 Value CONFIG_FILE (\S+)
 ```

2025-01-01 03:47 UTC, caribouHY commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +  ^WWAN\d?\s+.+$$
I added  a test case from command reference. I don't hava a device supported Wireless WAN and multiple USB ports.

2025-01-01 15:12 UTC, mjbear commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +  ^WWAN\d?\s+.+$$
> I added a test case from command reference. I don't hava a device supported Wireless WAN and multiple USB ports.

Understood.
I'd say that's reasonable. Thank you.

2025-01-07 17:16 UTC, jmcgill298 requested changes
Thanks @caribouHY , just a couple of minor updates

2025-01-07 17:16 UTC, jmcgill298 commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +Value SYSTEM (.+)
```suggestion
Value SYSTEM (.+?)
```
Need to limit this so that trailing whitespace is not captured

2025-01-07 17:16 UTC, jmcgill298 commented on ntc_templates/templates/fsas_sir_show_system_information.textfsm
> +Value CURRENT_TIME (.+)
```suggestion
Value STARTUP_TIME (.+?)
Value CURRENT_TIME (.+?)
```

2025-01-07 17:16 UTC, jmcgill298 commented on tests/fsas_sir/show_system_information/fasa_sir_show_system_information3.raw
> +WWAN1 Ver. : ------
```suggestion
WWAN1 Ver. : ------

```

2025-01-08 15:23 UTC, jmcgill298 approved these changes

2025-01-08 15:33 UTC, merged