Added Cisco IOS "show alert counters"
networktocode/ntc-templates pull request #793
Opened 2020-08-27 07:47 UTC by mjuenema

##### ISSUE TYPE

 - New Template Pull Request
 - Bugfix Pull Request
 - Additional Testing
 - Docs Pull Request

##### COMPONENT

##### SUMMARY

```

```

2020-08-27 13:23 UTC, mjuenema commented
For some obscure reason the tox test fails when the ```black``` command wants to re-format files which I haven't even changed. Even the ```master``` branch fails on my clone.
There seems to be a difference between black releases 19.x and 20.x. I opened a separate issues #794 for this.

2020-09-03 04:38 UTC, FragmentedPacket requested changes

2020-09-03 04:38 UTC, FragmentedPacket commented on tests/cisco_ios/show_alert_counters/cisco_ios_show_alert_counters.raw
> +
This template should still capture all the interfaces.

Look into the `-> Continue.Record` option to capture the same output you have plus the additional blank interfaces.

2020-11-12 19:19 UTC, jmcgill298 requested changes

2020-11-12 19:19 UTC, jmcgill298 commented on templates/cisco_ios_show_alert_counters.textfsm
> +
Need to match all possible lines, and add an error for any line that is not matched

2021-03-09 23:24 UTC, FragmentedPacket commented
Closing in favor of #881. @mjuenema Thanks for your contribution! I added the suggestions from @jmcgill298 to the new PR, and your commit is on that PR for credit for the work.

2021-03-09 23:24 UTC, closed without merging