New Template - hp_procurve_show_interfaces
networktocode/ntc-templates pull request #796
Opened 2020-08-27 21:00 UTC by adraf82

##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

hp_procurve_show_interfaces.textfsm

##### SUMMARY

I have added a new template for the 'show interfaces' command for a hp procurve device.

```

```

2020-09-06 19:45 UTC, adraf82 commented
Hi, has anyone been able to review my commits yet? Please can you advise if any amendments need to be made. This is my first pull request on GitHub. :-) Thanks

2020-10-20 22:11 UTC, jmcgill298 commented
Thanks Adraf82. The tests are failing, but I believe that if you rebase this with the current master, then they will likely pass. Please let us know if you need help with rebasing.

2020-10-20 22:24 UTC, jmcgill298 requested changes

2020-10-20 22:24 UTC, jmcgill298 commented on templates/index
> +hp_procurve_show_interfaces.textfsm, .*, hp_procurve, sh[[ow]] int[[erfaces]]
Please follow the entry rules:

```
# Rules of Ordering:
#  - OS in alphbetical order
#  - Command in length other
#  - When Length is the same, use alphabetical order
#  - Keep space between OS's
#
```

2020-10-21 20:25 UTC, adraf82 commented
Thanks for the reply Jacob. I have corrected the order for my template within the index file and have committed the change for merging.

I have rebased my repo and the test that was previously failing has passed.

Thanks

Adeel

Sent from my iPhone

On 20 Oct 2020, at 23:11, Jacob McGill <notifications@github.com> wrote:

﻿

Thanks Adraf82. The tests are failing, but I believe that if you rebase this with the current master, then they will likely pass. Please let us know if you need help with rebasing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/networktocode/ntc-templates/pull/796#issuecomment-713169481>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANIVDFYA2ZR3W4ALHRKBW2LSLYDJBANCNFSM4QNNGBOA>.

2020-10-21 22:06 UTC, jmcgill298 approved these changes

2020-10-21 22:07 UTC, merged

2020-10-21 22:07 UTC, jmcgill298 commented
Thanks @adraf82