Bugfix: IOS show lldp neig - fix neighbor name with spaces
networktocode/ntc-templates pull request #799
Opened 2020-09-08 07:21 UTC by realvitya

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT
cisco_ios_show_lldp_neighbor.textfsm, IOS, show lldp neighbor

##### SUMMARY
Fixed a case when neighbor name contained space (example included in the tests)

2020-09-08 07:30 UTC, realvitya commented
Test failings are not done by me. 😕

2020-10-20 22:22 UTC, jmcgill298 requested changes

2020-10-20 22:22 UTC, jmcgill298 commented on templates/index
> +cisco_ios_show_access-session.textfsm, .*, cisco_ios, show acce[[ss-session]]
```suggestion
cisco_ios_show_access-session.textfsm, .*, cisco_ios, show access-s[[ession]]
```
This change breaks show access-list as both are matching for `show acce`

2020-11-12 19:01 UTC, jmcgill298 approved these changes

2020-11-12 19:03 UTC, merged

2020-11-12 19:03 UTC, jmcgill298 commented
Thanks @realvitya