Bugfix: cisco_ios_show_running_partition_access_list
networktocode/ntc-templates pull request #808
Opened 2020-10-03 06:37 UTC by jpobeda

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT
cisco_ios_show_running_partition_access-list.textfsm
show running partition access-list

##### SUMMARY
Cisco IOS-XE outputs ACE line number on later versions.
Added Value LINE_NUM and made it backwards compatible.
Introduced Value ICMP_TYPE to amend capturing the icmp type eg: 'echo=reply'

2020-10-03 06:40 UTC, jpobeda commented
@jmcgill298 thanks for looking into this PR. I never learned to rebase without screwing the log :(
I'll push the other one soon.

2020-10-20 22:04 UTC, jmcgill298 requested changes
Same as #809

2020-10-26 04:35 UTC, jpobeda commented
@jmcgill298 I believe they should be fine now.

2020-10-26 17:58 UTC, jmcgill298 reviewed
Looks like there is still something a little off.

2020-10-26 17:58 UTC, jmcgill298 commented on tests/cisco_ios/show_running-config_partition_access-list/cisco_ios_show_running-config_partition_access-list_fixed.yml
> -    dst_port: "80"
looks like several of these are now capturing only the first char of the `dst_port`

2020-10-26 17:58 UTC, jmcgill298 commented on tests/cisco_ios/show_running-config_partition_access-list/cisco_ios_show_running-config_partition_access-list_fixed.yml
> -    log: "log"
This should still capture `log`

2020-10-26 20:32 UTC, jmcgill298 commented on tests/cisco_ios/show_running-config_partition_access-list/cisco_ios_show_running-config_partition_access-list.raw
> +access-list 101 permit tcp host 10.1.1.1 eq ftp any eq tacacs time-range test log
```suggestion
access-list 101 permit tcp host 10.1.1.1 eq ftp any eq tacacs log time-range test
```

2020-10-26 20:33 UTC, jmcgill298 commented on tests/cisco_ios/show_running-config_partition_access-list/cisco_ios_show_running-config_partition_access-list.yml
> +    log: ""
```suggestion
    log: "log"
```

2020-10-26 21:45 UTC, jmcgill298 approved these changes

2020-10-26 21:46 UTC, merged