Linux arp a
networktocode/ntc-templates pull request #814
Opened 2020-10-20 16:38 UTC by jifox

##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

linux_arp_a.textfsam, linux arp -a

##### SUMMARY

Parse arp-table `arp -a` on linux host

```
? (192.168.13.197) at 00:04:4b:cc:9c:ba [ether] on eth1.100
? (192.168.10.100) at <incomplete> on eth1.10
? (192.168.13.252) at 5c:e2:8c:fc:a4:74 [ether] on eth1.100
esxi (192.168.13.5) at 00:e0:67:05:9d:5a [ether] on eth1.100
? (192.168.13.253) at dc:f7:19:cd:d6:c4 [ether] on eth1.100
? (192.168.123.199) at 00:0f:c9:0e:c8:ec [ether] on eth0.21
? (192.168.10.52) at <incomplete> on eth1.10
? (192.168.10.7) at 00:0c:29:02:3b:93 [ether] on eth1.10
? (192.168.10.249) at 00:0c:29:bb:5f:a2 [ether] on eth1.10
```
```yaml
---
parsed_sample:
  - hw_type: "ether"
    interface: "eth1.100"
    ip_address: "192.168.13.197"
    mac_address: "00:04:4b:cc:9c:ba"
    rev_dns: "?"
  - hw_type: "ether"
    interface: "eth1.100"
    ip_address: "192.168.13.252"
    mac_address: "5c:e2:8c:fc:a4:74"
    rev_dns: "?"
  - hw_type: "ether"
    interface: "eth1.100"
    ip_address: "192.168.13.5"
    mac_address: "00:e0:67:05:9d:5a"
    rev_dns: "esxi"
  - hw_type: "ether"
    interface: "eth1.100"
    ip_address: "192.168.13.253"
    mac_address: "dc:f7:19:cd:d6:c4"
    rev_dns: "?"
  - hw_type: "ether"
    interface: "eth0.21"
    ip_address: "192.168.123.199"
    mac_address: "00:0f:c9:0e:c8:ec"
    rev_dns: "?"
  - hw_type: "ether"
    interface: "eth1.10"
    ip_address: "192.168.10.7"
    mac_address: "00:0c:29:02:3b:93"
    rev_dns: "?"
  - hw_type: "ether"
    interface: "eth1.10"
    ip_address: "192.168.10.249"
    mac_address: "00:0c:29:bb:5f:a2"
    rev_dns: "?"
```

2020-10-20 21:57 UTC, jmcgill298 requested changes
@jifox thanks for your contribution. The only thing missing is the validation that all output was captured as expected.

2020-10-20 21:57 UTC, jmcgill298 commented on templates/linux_arp_a.textfsm
> +  ^${REV_DNS}\s+\(${IP_ADDRESS}\)\s+at\s+${MAC_ADDRESS}\s+\[${HW_TYPE}\]\s+on\s+${INTERFACE}$$ -> Record
```suggestion
  ^${REV_DNS}\s+\(${IP_ADDRESS}\)\s+at\s+${MAC_ADDRESS}\s+\[${HW_TYPE}\]\s+on\s+${INTERFACE}$$ -> Record
  ^\s*$$
  ^. -> Error
```

2020-10-21 18:02 UTC, jifox commented
Hi @jmcgill298 

I've extended my set of test machines and saw that the cli output is translated on output. Therfore I've replaced the text constants ("at","on","auf") to \S+ so hopefully every language is accepted. I've also added regex for the <incomplete>-mac record.

I use the template already and it parses correctly, although the test is failing.


Value REV_DNS (\S+)
Value IP_ADDRESS (\S+)
Value MAC_ADDRESS (\S+)
Value HW_TYPE (\S+)
Value INTERFACE (\S+)

Start
  ^${REV_DNS}\s+\(${IP_ADDRESS}\)\s+\S+\s+${MAC_ADDRESS}\s+\[${HW_TYPE}\]\s+\S+\s+${INTERFACE}$$ -> Record
  ^${REV_DNS}\s+\(${IP_ADDRESS}\)\s+\S+\s+<${MAC_ADDRESS}>\s+\S+\s+${INTERFACE}$$ -> Record
  ^\s*$$
  ^. -> Error

2020-10-21 19:37 UTC, jmcgill298 commented
Should be fixed in https://github.com/jifox/ntc-templates/pull/1

2020-10-22 14:06 UTC, jmcgill298 approved these changes

2020-10-22 14:07 UTC, merged

2020-10-22 14:41 UTC, jifox commented
Thx for support