Add support for Arista EOS "show ipv6 bgp summary" and fix bug in "show ip bgp summary"
networktocode/ntc-templates pull request #864
Opened 2021-01-29 21:16 UTC by jsakofsky

##### ISSUE TYPE
 - New Template Pull Request
 - Bugfix Pull Request

##### COMPONENT
new: arista_eos_show_ipv6_bgp_summary
fix: arista_eos_show_ip_bgp_summary

##### SUMMARY
Added support for "show ipv6 bgp summary" based on the existing show ip bgp summary template.
Decided to add a new template due to changes to the bgp neighbor regex capture. There was also a bug in the existing show ip bgp summary template that broke parsing when the state indicated "Idle(NoIf)" due to attempt to capture a space that doesn't exist after field. I made the space optional, in case there was a circumstance where a space might exist.

2021-02-03 01:19 UTC, FragmentedPacket requested changes

2021-02-03 01:19 UTC, FragmentedPacket commented on templates/arista_eos_show_ip_bgp_summary.textfsm
> +  ^\s+${BGP_NEIGH}\s+\d+\s+${NEIGH_AS}\s+${MSG_RCVD}\s+${MSG_SENT}\s+${IN_QUEUE}\s+${OUT_QUEUE}\s+${UP_DOWN}\s+${STATE}\s* -> Record
Can you update one of the test files for this bug? Just to prevent regression in the future?

2022-12-24 21:09 UTC, itdependsnetworks commented
Replaced with #1264

2022-12-24 21:23 UTC, itdependsnetworks commented
Addressed in #1232

2022-12-24 21:23 UTC, closed without merging