add new template show port-security interface
networktocode/ntc-templates pull request #885
Opened 2021-03-11 20:59 UTC by jeffkala

##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

cisco_ios_show_port-security_interface.textfsm, cisco_ios, show port-security interface `interface`

##### SUMMARY

New template to parse the output of show port-security interface command.

```

```

2021-03-12 15:02 UTC, jmcgill298 commented
@jeffkala Unfortunately this PR wasn't passing tests last night when we migrated to poetry. Poetry does not allow us to package files outside of the package directory, so `templates` have moved to `ntc-templates/templates`. This branch will need to be rebased against master to fix the conflicts

2021-03-12 15:18 UTC, jeffkala commented
No problem @jmcgill298 , I have a few fixes to the template I need to do anyways.

2021-03-13 18:49 UTC, FragmentedPacket commented on ntc_templates/templates/index
> +cisco_ios_show_port-security_interface.textfsm, .*, cisco_ios, sh[[ow]] por[[t-security]] i[[nterface]](\s+\S+)
```suggestion
cisco_ios_show_port-security_interface.textfsm, .*, cisco_ios, sh[[ow]] por[[t-security]] i[[nterface]]
```

2021-03-13 18:50 UTC, FragmentedPacket requested changes
Just a small change for it to work to the index file and then revert the permissions on the `development_script.py`

2021-03-15 15:54 UTC, jeffkala commented
@FragmentedPacket , I did accept your suggestion, but not sure its accurate for my case.  Obviously I'm haivng some issues figuring it out myself.  The actual command would be `show port-security interface <interface name>`.  Last week when I talked to @jmcgill298 he helped me fix my test where I needed to change my folder name to `.._interface_interface`.  So i'm pretty confident my index file for this one needs to end with a regex to match the actual interface name?

2021-03-15 16:00 UTC, FragmentedPacket commented
That's fair. I'm not entirely sure, but when I messed with it, I couldn't get it working with the way it was originally setup with the RegEx in the index file. You can revert it and maybe hit up @jmcgill298 to see the way to do it. I'd be interested to see how to get it working as well.

2021-03-15 16:03 UTC, jeffkala commented
I put it back to the last regex I got working locally. using `.*` at the end.  I this is not the standard or recommended I can continue playing with it further.

2021-03-15 16:20 UTC, FragmentedPacket commented
👍 Awesome! That makes more sense now that the template has `_interface` at the end of it.

Do you mind just doing `chmod 755 development_scripts.py` to set it back to the original permissions?

2021-03-15 16:28 UTC, jeffkala commented
> 👍 Awesome! That makes more sense now that the template has `_interface` at the end of it.
> 
> Do you mind just doing `chmod 755 development_scripts.py` to set it back to the original permissions?

Done, sorry about that.

2021-03-15 16:55 UTC, FragmentedPacket approved these changes

2021-03-15 19:20 UTC, jmcgill298 approved these changes

2021-03-15 19:20 UTC, merged

2021-03-15 19:20 UTC, jmcgill298 commented
Thanks @jeffkala