New Template: alcatel_sros, sap-using
networktocode/ntc-templates pull request #892
Opened 2021-03-12 21:41 UTC by h4ndzdatm0ld

- New Template Pull Request

alcatel_sros_show_service_sap-using.textfsm,
alcatel_sros,
show service sap-using

2021-03-13 18:02 UTC, FragmentedPacket requested changes

2021-03-13 18:02 UTC, FragmentedPacket commented on ntc_templates/templates/alcatel_sros_show_service_sap-using.textfsm
> +  ^PortId\s+SvcId\s+Ing.\s+Ing.\s+Egr.\s+Egr.\s+Adm\s+Opr\s*$$
Transition based off header.

2021-03-14 04:42 UTC, FragmentedPacket approved these changes

2021-03-14 04:42 UTC, FragmentedPacket commented
@h4ndzdatm0ld Just need to rebase. This may happen for the next template as well.

2021-03-16 14:19 UTC, jmcgill298 approved these changes
Thanks @h4ndzdatm0ld 

Looks like you just need to fix the conflicts and this is ready to merge

2021-03-16 15:35 UTC, merged