New Template: alcatel_sros, sh router mpls lsp
networktocode/ntc-templates pull request #893
Opened 2021-03-12 22:40 UTC by h4ndzdatm0ld

- New Template Pull Request

alcatel_sros_show_router_mpls_lsp,
alcatel_sros,
"show router mpls lsp"

2021-03-13 18:08 UTC, FragmentedPacket requested changes

2021-03-13 18:08 UTC, FragmentedPacket commented on ntc_templates/templates/alcatel_sros_show_router_mpls_lsp.textfsm
> +Start
```suggestion
Start
  ^=+
```

2021-03-13 18:08 UTC, FragmentedPacket commented on ntc_templates/templates/alcatel_sros_show_router_mpls_lsp.textfsm
> +  ^MPLS\s+LSPs\s+\S+
```suggestion
  ^MPLS\s+LSPs
```
You don't need to account for the whole line if it's unique enough

2021-03-13 18:08 UTC, FragmentedPacket commented on ntc_templates/templates/alcatel_sros_show_router_mpls_lsp.textfsm
> +  ^LSP\s+Name\s+Tun\s+Fastfail\s+Adm\s+Opr\s*$$
```suggestion
  ^LSP\s+Name\s+Tun\s+Fastfail\s+Adm\s+Opr\s*$$ -> LSP
```

2021-03-13 18:08 UTC, FragmentedPacket commented on ntc_templates/templates/alcatel_sros_show_router_mpls_lsp.textfsm
> +  ^LSP\s+Name\s+Tun\s+Fastfail\s+Adm\s+Opr\s*$$
Move the other lines into the **LSP** state as well.

2021-03-13 22:18 UTC, h4ndzdatm0ld commented
Thanks @FragmentedPacket + Updates / Passing tests

2021-03-13 23:23 UTC, h4ndzdatm0ld reviewed
Looks good

2021-03-14 04:42 UTC, FragmentedPacket approved these changes

2021-03-15 23:06 UTC, h4ndzdatm0ld commented on ntc_templates/templates/index
> +<<<<<<< HEAD
Okie dokie ^_^

2021-03-16 15:38 UTC, FragmentedPacket commented
This has some changes from `master` included in it now. Let me know if you want me to help with getting it resolved.

2021-03-16 16:34 UTC, merged