Cisco IOS BFD neighbors details
networktocode/ntc-templates pull request #920
Opened 2021-04-12 02:08 UTC by mjbear

##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

cisco_ios_show_bfd_neighbors_details, cisco_ios, show bfd neighbors [ipv4|ipv6|client PROTOCOL] details

##### SUMMARY

Support parsing detailed BFD neighbor output. The template can parse IPv4, IPv6, or protocol specific BFD neighbors (see examples below).

Example Commands:
show bfd neighbors details
show bfd neighbors ipv6 details
show bfd neighbors client bgp details

```

```

2021-04-23 18:28 UTC, jvanderaa approved these changes

2021-04-23 18:30 UTC, jvanderaa requested changes
Add of the error on the Start and should be all set.

2021-04-23 18:30 UTC, jvanderaa commented on ntc_templates/templates/cisco_ios_show_bfd_neighbors_details.textfsm
> +
```suggestion
  ^. -> Error

```

2021-04-24 14:17 UTC, jvanderaa approved these changes

2021-04-24 14:17 UTC, merged

2021-04-24 14:24 UTC, mjbear commented
@jvanderaa : should the commit history have been re-written?
(or should have squashed them all into one "pretty" commit message?)

Notice how there a slew of commit messages from me on April 5 and April 11.
https://github.com/networktocode/ntc-templates/commits/master

2021-04-24 14:27 UTC, jvanderaa commented
@mjbear I'll check into that with @FragmentedPacket, @jmcgill298 and get that backed down to a single.

2021-04-24 15:54 UTC, jvanderaa commented
@mjbear it should be all set now. Thanks @FragmentedPacket

2021-04-24 16:20 UTC, mjbear commented
> @mjbear it should be all set now. Thanks @FragmentedPacket

Clean, so clean!
Much appreciated @jvanderaa and @FragmentedPacket